//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "books")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub summery: String,
    pub pdf_url: String,
    pub category_id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::category_book::Entity",
        from = "Column::CategoryId",
        to = "super::category_book::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CategoryBook,
}

impl Related<super::category_book::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryBook.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
