//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::books::Entity as Books;
pub use super::category_book::Entity as CategoryBook;
pub use super::posts::Entity as Posts;
pub use super::user::Entity as User;
